services:
  - type: web
    name: cortx-catalog-demo
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
